---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: polar-bear
  namespace: my-namespace
  labels:
    app.kubernetes.io/name: polar-bear
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: polar-bear
  template:
    metadata:
      labels:
        app.kubernetes.io/name: polar-bear
    spec:
      serviceAccountName: polar-bear
      automountServiceAccountToken: true
      containers:
        - name: server
          image: ghcr.io/geberl/polar-bear:2025.44.1
          imagePullPolicy: Always
          env:
            - name: POLAR_BEAR_LOGLEVEL
              value: info
            - name: POLAR_BEAR_HTTP_LISTEN_ADDRESS
              value: :8888
            - name: POLAR_BEAR_METRICS_LISTEN_ADDRESS
              value: :9100
            - name: POLAR_BEAR_CLUSTER_NAME
              value: my-cluster
            - name: POLAR_BEAR_HOSTNAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          ports:
            - name: http-web-svc
              containerPort: 8888
            - name: metrics
              containerPort: 9100
      imagePullSecrets:
        - name: ghcr
