---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: polar-bear
  namespace: my-namespace
  labels:
    app.kubernetes.io/name: polar-bear
spec:
  tls:
    - hosts:
        - plrbr.example.com
      secretName: example-cert
  rules:
    - host: plrbr.example.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: polar-bear
                port:
                  name: http-svc
