---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: polar-bear
  namespace: my-namespace
  labels:
    app.kubernetes.io/name: polar-bear
  annotations:
    kubernetes.io/service-account.name: polar-bear
