---
apiVersion: v1
kind: Service
metadata:
  name: polar-bear
  namespace: my-namespace
  labels:
    app.kubernetes.io/name: polar-bear
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: polar-bear
  ports:
    - name: http-svc
      port: 8888
      targetPort: http-web-svc
